######################################################################
#  Project
######################################################################

BINARY		= sevensegment
SRCFILES	= sevensegment.c

all: elf bin

include ../Makefile.incl

# End
