######################################################################
#  Project
######################################################################

BINARY		= buzzer
SRCFILES	= buzzer.c

all: elf bin

include ../Makefile.incl

# End
